###### general usage variables #####

# point spread function described as a flattened 3x3 array
psf: [0.5, 1.0, 0.5, 1.0, 3.0, 1.0, 0.5, 1.0, 0.5]

# place, where we keep LR images used in SR reconstruction
# if it doesn't exist then we will try to create this folder
samples_folder: 'input_samples'

# offset in (x,y) form for each low resolution image
offsets_of_captured_imgs: [[-1, -1], [0, -1], [1, -1],
                           [-1,  0],          [1,  0],
                           [-1,  1], [0,  1], [1,  1]]


##### variables specific to SR algorithm #####
iterations: 100

